## Assignment template 4) Plotting Tsunami locations with intensity frequency

This assignment follows on from 'Practical 6. Pandas data discovery - Geospatial analysis and plotting'. 

The data for this exercise is taken from:

 - [NCEI/WDS Global Historical Tsunami Database, 2100 BC to Present](https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.ngdc.mgg.hazards:G02151) doi:10.7289/V5PN93H7

The main objective is:

<div class="alert alert-block alert-success">
<b> Plot the location of Tsunami's as recorded in a given dataset and plot a histogram of intensity for those caused by Volcanos and Earthquakes</b> 
    
In this exercise you will need to work with data loaded into a Pandas dataframe. Aside from selecting those events that occured after the year 2000, you will also have to select recorded events that were not deemed to be caused by a 'Questionable Earthquake'. This is clarfied shortly.
  
Overview: You are tasked with:

 - 1. Loading a dataset of Tsunami events into a Pandas dataframe
 - 2. Extract data from this dataframe to plot global locations 
 - 3. Repeat the above but only where there event is not 'questionable' and occured after 2000
 - 4. Assess intensity for all non-questionable earthquakes caused from Volcanos and Earthquakes
 
According to the variable definitions provided on the [dataset webpage](https://www.ngdc.noaa.gov/hazard/tsu_db.shtml), the variable 'CAUSE_CODE', which you will find is stored in its own column in the dataframe, refers to the following options:

 - 0 = Unknown
 - 1 = Earthquake
 - 2 = Questionable Earthquake
 - 3 = Earthquake and Landslide
 - 4 = Volcano and Earthquake
 - 5 = Volcano, Earthquake, and Landslide
 - 6 = Volcano
 - 7 = Volcano and Landslide
 - 8 = Landslide
 - 9 = Meteorological
 - 10 = Explosion
 - 11 = Astronomical Tide
 
The variable 'SOLOVIEV' is a measure of Tsunami intensity.

Based on the example given in class, we can break this exercise down into a number of steps:

 - Load the data into a dataframe
 - Use the Cartopy package to plot the locations of each event
 - Draw a histogram of intensity for Tsunamis created by Volcanos and Earthquakes [seperately]
 
<div class="alert alert-block alert-warning">
<b>Please note:</b> 

We will discuss this in class, but aside from a working notebook we are also looking for the following:

 - An associated narrative with each operation. This includes the following sections:
 
  > Abstract
  - Summarise the project and main results

 > Introduction and methdology
  - What is the challenge and how are you solving it?
  - What modules/functions are you using?
  
 > Results
  - What is happening in each figure?
  
 We also want to see adequate referencing around:
  - What is the original source of the theory and/or data?
  - Comments in the code boxes using the # symbol. Remember that someone might not know what each line of code does.

You may also want to consider a broader discussion around this challenge. For example: 
 - What could be improved? 
 - How do you know your results are correct? [i.e. what might improve trust in your simulations?]
 - What if someone wanted to get in touch with you and re-use this code? Any restrictions on data?

To start, we reccomend you first get the code implementation working and then construct the narrative around it. Also please note that to add another code or markdown box, you can simple use the 'Insert' option on the main menu.

Your plot of locations and histogram of earthquake derived intensity should resemble the following figures:

<table><tr>
    <td> <img src="images/Assessment4_output1a.png" alt="Drawing" style="width: 350px;"/> </td>
    <td> <img src="images/Assessment4_output1.png" alt="Drawing" style="width: 350px;"/> </td>
</tr></table>


Please note that you can load your data, once the Pandas module has been imported, using the following commands:

```python
data = pd.read_csv("data/tsevent.csv") 
```

</div>

</div>

## Abstract

## Introduction

## Methodology

In [1]:
#### -------- INSERT CODE HERE ----------
import pandas as pd #Im using pd here as its easier to keep writing! You can use whatever you want, but it might help you to use 'pd' for now.

# Read data from file 'GVP_Eruption_Results.csv' 
# We are going to use the function 'read_csv' within the Pandas package:


# Notice how we call that function using the '.' operator?
# (Note the data file needs to be in the same directory that your jupyter notebook is based) You can control delimiters, rows, column names with read_csv (see later) 
data = pd.read_csv("data/tsevent.csv") 

# How do we preview the data file.
# Preview the first 5 lines of the loaded data 
data.head()

#### ------------------------------------

,ID,YEAR,MONTH,DAY,HOUR,MINUTE,SECOND,EVENT_VALIDITY,CAUSE_CODE,FOCAL_DEPTH,...,TOTAL_MISSING,TOTAL_MISSING_DESCRIPTION,TOTAL_INJURIES,TOTAL_INJURIES_DESCRIPTION,TOTAL_DAMAGE_MILLIONS_DOLLARS,TOTAL_DAMAGE_DESCRIPTION,TOTAL_HOUSES_DESTROYED,TOTAL_HOUSES_DESTROYED_DESCRIPTION,TOTAL_HOUSES_DAMAGED,TOTAL_HOUSES_DAMAGED_DESCRIPTION
0,1,-2000,NaN,NaN,NaN,NaN,NaN,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
1,3,-1610,NaN,NaN,NaN,NaN,NaN,4,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
2,4,-1365,NaN,NaN,NaN,NaN,NaN,1,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
3,5,-1300,NaN,NaN,NaN,NaN,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,-760,NaN,NaN,NaN,NaN,NaN,2,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Results


#### references